# Generated by Django 4.0.3 on 2022-04-08 07:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_title', models.CharField(choices=[('introduction to hacking', 'Introduction To Hacking'), ('footprinting', 'Footprinting'), ('network scaning', 'Network Scanning'), ('enumeration', 'Enumeration'), ('vulnerability Analysis', 'Vulnerability Analysis'), ('system hacking', 'System Hacking'), ('malware analysis', 'Malware Analysis'), ('sniffing', 'Sniffing'), ('social engineering', 'Social Engineering'), ('denieal of service attack', 'Denieal Of Service Attack'), ('session hijacking', 'Session Hijacking'), ('firewall', 'Firewall Ids Ips Honeypots'), ('hacking web servers', 'Hacking Web Servers'), ('hacking web applications', 'Hacking Web Applications'), ('sql injection', 'Sql Injection'), ('hacking mobile platforms', 'Hacking Mobile Platforms'), ('wifi hacking', 'Wifi Hacking'), ('IOT hacking', 'Iot Hacking'), ('cloud computing', 'Cloud Computing'), ('cryptography', 'Cryptography')], default='introduction to hacking', max_length=300)),
                ('module_slug', models.SlugField()),
                ('module_photos', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('module_description', models.TextField()),
                ('module_content', models.TextField()),
                ('module_level', models.IntegerField()),
                ('module_difficulty', models.CharField(max_length=100)),
                ('module_area', models.CharField(max_length=100)),
                ('module_sections', models.IntegerField()),
                ('module_points_add', models.IntegerField()),
                ('module_points_minus', models.IntegerField()),
                ('module_date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=300)),
                ('topic_slug', models.SlugField()),
                ('topic_description', models.TextField()),
                ('topic_content', models.TextField()),
                ('topic_number', models.IntegerField()),
                ('topic_date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='moduletopic', to='modules.module', verbose_name='squadra')),
            ],
        ),
    ]
