# Generated by Django 4.0.3 on 2022-03-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_topic_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_title',
            field=models.CharField(max_length=300),
        ),
    ]
