# Generated by Django 4.0.3 on 2022-04-02 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_alter_topic_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='moduletopic', to='modules.module', verbose_name='squadra'),
        ),
    ]
