# Generated by Django 4.0.3 on 2022-04-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctfs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctfs',
            name='ctfs_topic_list',
        ),
        migrations.AddField(
            model_name='ctfstopic',
            name='ctfs_topic_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctfstopic',
            name='ctfs_topic_difficulty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ctfstopic',
            name='ctfs_topic_points_add',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctfstopic',
            name='ctfs_topic_points_minus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctfs',
            name='ctfs_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ctfs',
            name='ctfs_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctfs',
            name='ctfs_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctfs',
            name='ctfs_difficulty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ctfs',
            name='ctfs_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctfs',
            name='ctfs_points_add',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctfs',
            name='ctfs_points_minus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctfs',
            name='ctfs_sections',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctfs',
            name='ctfs_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctfstopic',
            name='ctfs_topic_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctfstopic',
            name='ctfs_topic_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctfstopic',
            name='ctfs_topic_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctfstopic',
            name='ctfs_topic_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
