# Generated by Django 4.0.3 on 2022-04-08 07:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_title', models.CharField(choices=[('introduction to ethical hacking labs', 'Introduction To Ethical Hacking Labs'), ('footprinting labs', 'Footprinting Labs'), ('network scaning labs', 'Network Scanning Labs'), ('enumeration labs', 'Enumeration Labs'), ('vulnerability Analysis labs', 'Vulnerability Analysis Labs'), ('system hacking labs', 'System Hacking Labs'), ('malware analysis labs', 'Malware Analysis Labs'), ('sniffing labs', 'Sniffing Labs'), ('social engineering labs', 'Social Engineering Labs'), ('denieal of service attack labs', 'Denieal Of Service Attack Labs'), ('session hijacking labs', 'Session Hijacking Labs'), ('firewall labs', 'Firewall Ids Ips Honeypots Labs'), ('hacking web servers labs', 'Hacking Web Servers Labs'), ('hacking web applications labs', 'Hacking Web Applications Labs'), ('sql injection labs', 'Sql Injection Labs'), ('hacking mobile platforms labs', 'Hacking Mobile Platforms Labs'), ('wifi hacking labs', 'Wifi Hacking Labs'), ('iot labs', 'Iot Labs'), ('cloud computing labs', 'Cloud Computing Labs'), ('cryptography labs', 'Cryptography Labs')], default='introduction to ethical hacking labs', max_length=300)),
                ('lab_slug', models.SlugField()),
                ('lab_photos', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('lab_description', models.TextField()),
                ('lab_content', models.TextField()),
                ('lab_level', models.IntegerField()),
                ('lab_difficulty', models.CharField(max_length=100)),
                ('lab_area', models.CharField(max_length=100)),
                ('lab_sections', models.IntegerField()),
                ('lab_points_add', models.IntegerField()),
                ('lab_points_minus', models.IntegerField()),
                ('lab_date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_topic_title', models.CharField(max_length=300)),
                ('lab_topic_slug', models.SlugField()),
                ('lab_topic_description', models.TextField()),
                ('lab_topic_content', models.TextField()),
                ('lab_topic_number', models.IntegerField()),
                ('lab_topic_date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='labs.labs')),
            ],
        ),
    ]
