# Generated by Django 4.0.3 on 2022-03-27 03:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_alter_labpost_lab_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_title', models.CharField(choices=[('introduction', 'Introduction'), ('footprinting', 'Footprinting'), ('network scaning', 'Network Scanning'), ('enumeration', 'Enumeration'), ('vulnerability Analysis', 'Vulnerability Analysis'), ('system hacking', 'System Hacking'), ('malware analysis', 'Malware Analysis'), ('sniffing', 'Sniffing'), ('social engineering', 'Social Engineering'), ('denieal of service attack', 'Denieal Of Service Attack'), ('session hijacking', 'Session Hijacking'), ('firewall', 'Firewall Ids Ips Honeypots'), ('hacking web servers', 'Hacking Web Servers'), ('hacking web applications', 'Hacking Web Applications'), ('sql injection', 'Sql Injection'), ('hacking mobile platforms', 'Hacking Mobile Platforms'), ('wifi hacking', 'Wifi Hacking'), ('iot', 'Iot'), ('cloud computing', 'Cloud Computing'), ('cryptography', 'Cryptography')], default='introduction', max_length=50)),
                ('lab_slug', models.SlugField()),
                ('lab_photos', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('lab_description', models.TextField()),
                ('lab_content', models.TextField()),
                ('lab_level', models.IntegerField()),
                ('lab_difficulty', models.CharField(max_length=100)),
                ('lab_area', models.CharField(max_length=100)),
                ('lab_sections', models.IntegerField()),
                ('lab_points_add', models.IntegerField()),
                ('lab_points_minus', models.IntegerField()),
                ('lab_date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('lab_topic_list', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_topic_title', models.CharField(max_length=300)),
                ('lab_topic_slug', models.SlugField()),
                ('lab_topic_description', models.TextField()),
                ('lab_topic_content', models.TextField()),
                ('lab_topic_number', models.IntegerField()),
                ('lab_topic_date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='labs.labs')),
            ],
        ),
        migrations.DeleteModel(
            name='LabPost',
        ),
    ]
